### ISSUE TITLE
[BUG] Pypi stats dropped to zero

### ISSUE THREAD

**Issue by axsaucedo** [hugovk/pypistats#300] opened 2021-12-07 08:06 UTC
Just a heads up that it seems the pypi stats for most projects seem to have dropped to zero for the last couple of days.

Example with MLFLow https://pypistats.org/packages/mlflow:

![image](https://user-images.githubusercontent.com/1447507/144990401-f4f5ea81-85eb-4fbc-a1e4-747aad93118b.png)

**Comment by hugovk** [comment] 2021-12-07 08:20
Thanks, duplicate of https://github.com/hugovk/pypistats/issues/299.

**Closed** 2021-12-07 08:21 UTC

**Comment by axsaucedo** [comment] 2021-12-07 08:52
Perfect - thank you!
